// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Home = require("./Home.bs.js");
var Serbet = require("serbet/src/Serbet.bs.js");
var HelloJson = require("./HelloJson.bs.js");

var app = Serbet.application(undefined, {
      hd: HelloJson.endpoint,
      tl: {
        hd: Home.endpoint,
        tl: /* [] */0
      }
    });

exports.app = app;
/* app Not a pure module */
