// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Async = require("serbet/src/Async.bs.js");
var Decco = require("decco/src/Decco.js");
var Serbet = require("serbet/src/Serbet.bs.js");
var Js_dict = require("bs-platform/lib/js/js_dict.js");
var Js_json = require("bs-platform/lib/js/js_json.js");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");

function body_out_encode(v) {
  return Js_dict.fromArray([[
                "message",
                Decco.stringToJson(v.message)
              ]]);
}

function body_out_decode(v) {
  var dict = Js_json.classify(v);
  if (typeof dict === "number") {
    return Decco.error(undefined, "Not an object", v);
  }
  if (dict.TAG !== /* JSONObject */2) {
    return Decco.error(undefined, "Not an object", v);
  }
  var message = Decco.stringFromJson(Belt_Option.getWithDefault(Js_dict.get(dict._0, "message"), null));
  if (!message.TAG) {
    return {
            TAG: /* Ok */0,
            _0: {
              message: message._0
            }
          };
  }
  var e = message._0;
  return {
          TAG: /* Error */1,
          _0: {
            path: ".message" + e.path,
            message: e.message,
            value: e.value
          }
        };
}

var endpoint = Serbet.endpoint(undefined, {
      path: "/",
      verb: /* GET */0,
      handler: (function (_req) {
          return Async.async({
                      TAG: /* OkJson */4,
                      _0: body_out_encode({
                            message: "Bom dia"
                          })
                    });
        })
    });

exports.body_out_encode = body_out_encode;
exports.body_out_decode = body_out_decode;
exports.endpoint = endpoint;
/* endpoint Not a pure module */
